dist: trusty
sudo: false

language: python
python:
    - "3.6"

install:
    - "pip install vim-vint"

before_script:
    - "git clone https://github.com/junegunn/vader.vim.git"

script:
    - vint behave.vim
    - |
      cd tests &&
      vim -Nu <(cat << VIMRC
      filetype off
      set rtp+=vader.vim
      set rtp+=.
      filetype plugin indent on
      syntax enable
      VIMRC) -c 'Vader! *.vader' > /dev/null
